db.url: jdbc:mysql://${db.host}:${db.port}/${db.name}

db:
  host: localhost
  port: 3306
  name: fourfrika
  username: root
  password:

spring:
  jmx.enabled: true
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    properties.hibernate:
      default_schema: fourfrika
      enable_lazy_load_no_trans: true
      dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    initialize: true
    validation-query: "SELECT version();"
    test-on-borrow: true
    min-idle: 10
    max-idle: 10
    initial-size: 10
    max-active: 100
    jmx-enabled: true

custom:
  datasource:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048


logging.level.org.apache: DEBUG
logging.level.org.hibernate: DEBUG

logging.level.com.groupon: DEBUG
logging.level.org.springframework.integration: DEBUG
logging.level.org.springframework.test: DEBUG
logging.level.org.springframework.boot.context.config.ConfigFileApplicationListener: DEBUG

flyway:
  enabled: false #prevent spring from initializing flyway flyway.enabled: false