db.url: jdbc:mysql://${db.host}:${db.port}/${db.name}

db:
  host: localhost
  port: 3306
  name: ${app.name}
  username: root
  password:

spring:
  jmx.enabled: true
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    properties.hibernate:
      default_schema: ${db.name}
      enable_lazy_load_no_trans: true
      dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    validation-query: "SELECT version();"
    test-on-borrow: true
    min-idle: 10
    max-idle: 10
    initial-size: 10
    max-active: 100
    jmx-enabled: true

custom:
  datasource:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048

#logging
logging.config: classpath:config/logback/logback-dev.xml
logging.level.org: ERROR
logging.level.jdbc: ERROR

# Change the following logs to DEBUG in order to monitor issues
# Change the following to info (logging.level... org, jdbc.sqlonly, springframework.context.cache)

logging.level.jdbc.sqlonly: ERROR
logging.level.jdbc.sqltiming: ERROR
logging.level.jdbc.audit: ERROR
logging.level.jdbc.resultset: ERROR
logging.level.jdbc.connection: ERROR
logging.level.org.hibernate.engine: ERROR
logging.level.org.hibernate.loader: ERROR
logging.level.org.hibernate.hql: ERROR
logging.level.org.hibernate.SQL: ERROR
logging.level.org.hibernate.jpa: ERROR
logging.level.org.hibernate.persister: ERROR
logging.level.org.hibernate.cfg: ERROR
logging.level.org.hibernate.type: ERROR   #Shows the types hibernate is adding to context
logging.level.jdbc.resultsettable: ERROR  #Plain text version of table with data

# hibernate context
logging.level.org.hibernate.validator.internal: ERROR
logging.level.org.hibernate.jpa.internal: ERROR
logging.level.org.hibernate.integrator.internal: ERROR
logging.level.org.hibernate.boot.registry.internal: ERROR
logging.level.org.hibernate.id.factory.internal: ERROR  #id generation info
logging.level.org.hibernate.internal: ERROR  #Display properties of the session factory
logging.level.org.event.internal: ERROR  #Display properties of the session factory

#Spring boot context info
logging.level.org.springframework.boot.context: ERROR
logging.level.org.springframework.web.context: ERROR
logging.level.org.springframework.context: ERROR
logging.level.org.springframework.boot.context.config.ConfigFileApplicationListener: ERROR
logging.level.org.springframework.context.cache: ERROR  #cache stats during tests. Too many misses => reduce use of @DirtiesContext
logging.level.org.springframework.test: ERROR  #These libs will debug until this config is loaded and set


flyway:
  enabled: false #prevent spring from initializing flyway flyway.enabled: false