#spring.profiles.active: dev  # This will not work simply because it is overridden by "@ActiveProfiles(value = {"test"})" on test methods. see
#spring.profiles.include: prod #for testing prod locally
spring.profiles.include: dev
