db.url: jdbc:mysql://${db.host}:${db.port}/${db.name}

db:
  host: localhost
  port: 3306
  name: fourfrika
  username: root
  password:

spring:
  jmx.enabled: true
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    properties.hibernate:
      default_schema: fourfrika
      enable_lazy_load_no_trans: true
      dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    initialize: true
    validation-query: "SELECT version();"
    test-on-borrow: true
    min-idle: 10
    max-idle: 10
    initial-size: 10
    max-active: 100
    jmx-enabled: true

custom:
  datasource:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048


flyway:
  enabled: false #prevent spring from initializing flyway flyway.enabled: false

spring.profiles.include: local

#logging
# default location is directly in the classpath
logging.config: classpath:config/logback/logback.xml


##Tomcat log
# Directory in which log files are created. Can be relative to the tomcat base dir or absolute.
server.tomcat.accesslog.directory: /usr/local/var/log
server.tomcat.accesslog.enabled: true
server.tomcat.accesslog.pattern: "%{yyyy-MM-dd HH:mm:ss.SSS}t %a (%{X-Forwarded-For}i) > %A:%p '%r' %{requestBodyLength}r %D %s %B %I '%{Referer}i' '%{User-Agent}i' %u %{username}s %{sessionTracker}s"
server.tomcat.accesslog.prefix: access_log
server.tomcat.accesslog.suffix: .log
